### ISSUE TITLE
reportTestCaseResult(projectName, testPlanName, testCaseNameOrVisibleID, buildName, execNotes, testResultStatus) gives testlink.api.java.client.TestLinkAPIException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [aaporjr/testlink-api-client#7]
```
What steps will reproduce the problem?
1. I am using latest testlink-1.9.5 version to integrate my selenium tests
2. I have added all testlink api client files to my project
3. While executing it i am getting following exception and it is pointing to 
the line:
testlinkAPIClient.reportTestCaseResult(PROJECT_NAME, TESTPLAN_NAME, 
TESTCASE_NAME, BUILD_NAME, notes, result);

Exception: 
[Fatal Error] :3:6: The processing instruction target matching "[xX][mM][lL]" 
is not allowed.
[Fatal Error] :3:6: The processing instruction target matching "[xX][mM][lL]" 
is not allowed.
[Fatal Error] :3:6: The processing instruction target matching "[xX][mM][lL]" 
is not allowed.
[Fatal Error] :3:6: The processing instruction target matching "[xX][mM][lL]" 
is not allowed.
testlink.api.java.client.TestLinkAPIException: The call to the xml-rpc client 
failed.
    at testlink.api.java.client.TestLinkAPIClient.executeXmlRpcMethod(TestLinkAPIClient.java:1266)
    at testlink.api.java.client.TestLinkAPIClient.execXmlRpcMethodWithCache(TestLinkAPIClient.java:1195)
    at testlink.api.java.client.TestLinkAPIClient.getProjects(TestLinkAPIClient.java:726)
    at testlink.api.java.client.TestLinkAPIHelper.getProjectInfo(TestLinkAPIHelper.java:64)
    at testlink.api.java.client.TestLinkAPIHelper.getProjectID(TestLinkAPIHelper.java:48)
    at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:184)
    at Pack3.ResultTestlink.reportTestCaseResult1(ResultTestlink.java:11)
    at Pack3.TestlinkExcecution.f(TestlinkExcecution.java:62)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
    at java.lang.reflect.Method.invoke(Unknown Source)
    at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
    at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
    at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
    at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
    at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
    at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
    at org.testng.TestRunner.privateRun(TestRunner.java:767)
    at org.testng.TestRunner.run(TestRunner.java:617)
    at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
    at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
    at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
    at org.testng.SuiteRunner.run(SuiteRunner.java:240)
    at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
    at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
    at org.testng.TestNG.runSuitesSequentially(TestNG.java:1203)
    at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
    at org.testng.TestNG.run(TestNG.java:1036)
    at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
Caused by: org.apache.xmlrpc.client.XmlRpcClientException: Failed to parse 
servers response: The processing instruction target matching "[xX][mM][lL]" is 
not allowed.
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:177)
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:145)
    at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:94)
    at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:44)
    at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:53)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:166)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:157)
    at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:146)
    at testlink.api.java.client.TestLinkAPIClient.executeXmlRpcMethod(TestLinkAPIClient.java:1232)
    ... 31 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 6; The 
processing instruction target matching "[xX][mM][lL]" is not allowed.
    at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
    at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
    at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:175)
    ... 39 more

What is the expected output? What do you see instead?
it should not raise any exception and it should update the result in the 
specified test case. 

What version of the product are you using? On what operating system?
Testlink-1.9.5
Windows 7
Apache 2.4.2
php 5.4.3
My sql 5.5.24

Please provide any additional information below.
Please let me know the cause for this exception as early as possible. Thanks in 
Advance
```

Original issue reported on code.google.com by `vikasco...@gmail.com` on 28 Feb 2013 at 11:47

**Comment by MM-Ironman** [comment]
D

> ```
> What steps will reproduce the problem?
> 1. I am using latest testlink-1.9.5 version to integrate my selenium tests
> 2. I have added all testlink api client files to my project
> 3. While executing it i am getting following exception and it is pointing to 
> the line:
> testlinkAPIClient.reportTestCaseResult(PROJECT_NAME, TESTPLAN_NAME, 
> TESTCASE_NAME, BUILD_NAME, notes, result);
> 
> Exception: 
> [Fatal Error] :3:6: The processing instruction target matching "[xX][mM][lL]" 
> is not allowed.
> [Fatal Error] :3:6: The processing instruction target matching "[xX][mM][lL]" 
> is not allowed.
> [Fatal Error] :3:6: The processing instruction target matching "[xX][mM][lL]" 
> is not allowed.
> [Fatal Error] :3:6: The processing instruction target matching "[xX][mM][lL]" 
> is not allowed.
> testlink.api.java.client.TestLinkAPIException: The call to the xml-rpc client 
> failed.
>     at testlink.api.java.client.TestLinkAPIClient.executeXmlRpcMethod(TestLinkAPIClient.java:1266)
>     at testlink.api.java.client.TestLinkAPIClient.execXmlRpcMethodWithCache(TestLinkAPIClient.java:1195)
>     at testlink.api.java.client.TestLinkAPIClient.getProjects(TestLinkAPIClient.java:726)
>     at testlink.api.java.client.TestLinkAPIHelper.getProjectInfo(TestLinkAPIHelper.java:64)
>     at testlink.api.java.client.TestLinkAPIHelper.getProjectID(TestLinkAPIHelper.java:48)
>     at testlink.api.java.client.TestLinkAPIClient.reportTestCaseResult(TestLinkAPIClient.java:184)
>     at Pack3.ResultTestlink.reportTestCaseResult1(ResultTestlink.java:11)
>     at Pack3.TestlinkExcecution.f(TestlinkExcecution.java:62)
>     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>     at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
>     at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
>     at java.lang.reflect.Method.invoke(Unknown Source)
>     at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:80)
>     at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
>     at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
>     at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
>     at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:128)
>     at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
>     at org.testng.TestRunner.privateRun(TestRunner.java:767)
>     at org.testng.TestRunner.run(TestRunner.java:617)
>     at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
>     at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
>     at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
>     at org.testng.SuiteRunner.run(SuiteRunner.java:240)
>     at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
>     at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
>     at org.testng.TestNG.runSuitesSequentially(TestNG.java:1203)
>     at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
>     at org.testng.TestNG.run(TestNG.java:1036)
>     at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
>     at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
>     at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
> Caused by: org.apache.xmlrpc.client.XmlRpcClientException: Failed to parse 
> servers response: The processing instruction target matching "[xX][mM][lL]" is 
> not allowed.
>     at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:177)
>     at org.apache.xmlrpc.client.XmlRpcStreamTransport.sendRequest(XmlRpcStreamTransport.java:145)
>     at org.apache.xmlrpc.client.XmlRpcHttpTransport.sendRequest(XmlRpcHttpTransport.java:94)
>     at org.apache.xmlrpc.client.XmlRpcSunHttpTransport.sendRequest(XmlRpcSunHttpTransport.java:44)
>     at org.apache.xmlrpc.client.XmlRpcClientWorker.execute(XmlRpcClientWorker.java:53)
>     at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:166)
>     at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:157)
>     at org.apache.xmlrpc.client.XmlRpcClient.execute(XmlRpcClient.java:146)
>     at testlink.api.java.client.TestLinkAPIClient.executeXmlRpcMethod(TestLinkAPIClient.java:1232)
>     ... 31 more
> Caused by: org.xml.sax.SAXParseException; lineNumber: 3; columnNumber: 6; The 
> processing instruction target matching "[xX][mM][lL]" is not allowed.
>     at org.apache.xerces.parsers.AbstractSAXParser.parse(Unknown Source)
>     at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
>     at org.apache.xmlrpc.client.XmlRpcStreamTransport.readResponse(XmlRpcStreamTransport.java:175)
>     ... 39 more
> 
> What is the expected output? What do you see instead?
> it should not raise any exception and it should update the result in the 
> specified test case. 
> 
> What version of the product are you using? On what operating system?
> Testlink-1.9.5
> Windows 7
> Apache 2.4.2
> php 5.4.3
> My sql 5.5.24
> 
> Please provide any additional information below.
> Please let me know the cause for this exception as early as possible. Thanks in 
> Advance
> ```
> 
> Original issue reported on code.google.com by `vikasco...@gmail.com` on 28 Feb 2013 at 11:47

Hi, have you solved this issue?
If so, please help me for solving this issue.
I am getting the same error.
